type: docker

restapi:
  port: 44044
  write_timeout: 20s
  read_timeout: 10s
  shutdown_timeout: 10s
  request_timeout: 15s
  mode: debug
  cookie-ttl: 1h

grpc:
  port: 44045
  timeout: 30s

logger:
  level: debug
