type: docker

restapi:
  port: 44044
  write_timeout: 20s
  read_timeout: 10s
  shutdown_timeout: 10s
  request_timeout: 15s
  mode: debug

grpc:
  port: 44045
  timeout: 30s

connections:
  projectservice:
    port: 44046
    timeout: 5s
  taskservice:
    port: 44047
    timeout: 5s

logger:
  level: debug
