restapi:
  port: 44044
  timeout: 30s

grpc:
  port: 44045
  timeout: 30s

connections:
  projectservice:
    port: 44046
    timeout: 5s
  taskservice:
    port: 44047
    timeout: 5s

postgres:
  host: localhost
  port: 5432
  user: app_user
  db_name: users
  password: app_user_pass
  sslmode: disable

logger:
  level: debug

redis:
