type: local

restapi:
  port: 44044
  write_timeout: 20s
  read_timeout: 10s
  shutdown_timeout: 10s
  request_timeout: 15s
  mode: debug

grpc:
  port: 44045
  timeout: 30s

connections:
  projectservice:
    port: 44046
    timeout: 5s
  taskservice:
    port: 44047
    timeout: 5s

postgres:
  host: localhost
  port: 5432
  user: app_user
  db_name: users
  #password in .env file
  sslmode: disable

logger:
  level: debug

redis:
  host: localhost
  port: 6379
  #password in .env file
  db: 0
